### ISSUE TITLE
Trouble installing colorblindr

### ISSUE THREAD

**Issue by clarashaw** [clauswilke/colorblindr#5]
Hi Claus,

I'm trying to install the colorblindr package with the following command on my windows computer with R version 3.4.2: devtools::install_github("clauswilke/colorblindr")

It looks like the installation is failing because it's not working correctly with colorspace. The error I get is:

preparing package for lazy loading
Error : object 'deutan' is not exported by 'namespace:colorspace'
ERROR: lazy loading failed for package 'colorblindr'
removing 'C:/Users/ClaraShaw/Documents/R/win-library/3.4/colorblindr'
Installation failed: Command failed (1)

I installed cowplot and colorspace today, so I'm not sure what's wrong, and I couldn't find much on troubleshooting this issue. 

Thanks so much for your help!
-Clara

**Comment by clauswilke** [comment]
You need version 1.4-0 of colorspace. It can be installed from here: https://r-forge.r-project.org/R/?group_id=20 But install on windows sometimes is problematic. Let me know if it doesn't work.

**Comment by clairemcwhite** [comment]
Hi Clara,

Did you install colorspace with

install.packages("colorspace", repos = "http://R-Forge.R-project.org")



On Nov 29, 2017 3:55 PM, "clarashaw" <notifications@github.com> wrote:

Hi Claus,

I'm trying to install the colorblindr package with the following command on
my windows computer with R version 3.4.2: devtools::install_github("clau
swilke/colorblindr")

It looks like the installation is failing because it's not working
correctly with colorspace. The error I get is:

** preparing package for lazy loading
Error : object 'deutan' is not exported by 'namespace:colorspace'
ERROR: lazy loading failed for package 'colorblindr'

   - removing 'C:/Users/ClaraShaw/Documents/R/win-library/3.4/colorblindr'
   Installation failed: Command failed (1)

I installed cowplot and colorspace today, so I'm not sure what's wrong, and
I couldn't find much on troubleshooting this issue.

Thanks so much for your help!
-Clara

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/clauswilke/colorblindr/issues/5>, or mute the thread

**Comment by clarashaw** [comment]
Hi,

Thanks Claus and Clair, I used install.packages("colorspace", repos = "http://R-Forge.R-project.org"), and then installed colorblindr again and it worked! Thank you!

Now when attempting cvd_grid(), I get an error:
Error in eval(`_inherit`, env, NULL) : object 'ScalesList' not found
I think this may be because of my cowplot package because I've seen that error before when using it.

**Comment by clauswilke** [comment]
Can you provide the output from `sessionInfo()`, please? And also a backtrace if possible?

**Comment by clarashaw** [comment]
Here is the output of sessionInfo()

R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] cowplot_0.9.1     colorblindr_0.1.0 ggplot2_2.2.1    
[4] colorspace_1.4-0  lme4_1.1-14       Matrix_1.2-11    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14    knitr_1.17      splines_3.4.2  
 [4] devtools_1.13.4 MASS_7.3-47     munsell_0.4.3  
 [7] lattice_0.20-35 R6_2.2.2        rlang_0.1.4    
[10] minqa_1.2.4     plyr_1.8.4      httr_1.3.1     
[13] tools_3.4.2     grid_3.4.2      gtable_0.2.0   
[16] nlme_3.1-131    git2r_0.19.0    withr_2.1.0    
[19] lazyeval_0.2.1  digest_0.6.12   tibble_1.3.4   
[22] nloptr_1.0.4    curl_3.0        memoise_1.1.0  
[25] compiler_3.4.2  scales_0.5.0

**Comment by clarashaw** [comment]
Got it figured out! My RStudio was too old. Sorry to bring up this problem!

**Comment by clairemcwhite** [comment]
That's alright!

I'll update our readme to be more clear.  I actually had the same deutan
error recently.

Claire

On Nov 29, 2017 8:12 PM, "clarashaw" <notifications@github.com> wrote:

Got it figured out! My RStudio was too old. Sorry to bring up this problem!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/clauswilke/colorblindr/issues/5#issuecomment-348060665>,
or mute the thread
